### ISSUE TITLE
Gray out the playlists until choosing a device

### ISSUE THREAD

**Issue by idoaflalo** [custom-cards/spotify-card#114]
title^

**Comment by FL550** [comment]
What would be the benefit of this?

**Comment by idoaflalo** [comment]
It's a little weird that you can pick up a playlist before choosing a device to play it.

**Comment by FL550** [comment]
Hm, I think it's not very appealing if the playlists are grey when you load the card with no default player.

A suggestion for this to make both of us happy: make the covers gray when there is no player available for playback and otherwise start playback on the first device available when none is selected. 

@fondberg what are your thoughts on this?

**Comment by idoaflalo** [comment]
> Hm, I think it's not very appealing if the playlists are grey when you load the card with no default player.
> 
> A suggestion for this to make both of us happy: make the covers gray when there is no player available for playback and otherwise start playback on the first device available when none is selected.
> 
> @fondberg what are your thoughts on this?

Sound pretty good and easy to implement using the filter property:

 https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/grayscale

**Comment by FL550** [comment]
We are working on this: #118

**Comment by FL550** [comment]
This is now implemented.
