### ISSUE TITLE
INVALID_CLIENT: Invalid redirect URI

### ISSUE THREAD

**Issue by crimean7** [custom-cards/spotify-card#19]
Getting INVALID_CLIENT: Invalid redirect URI.

- Have https://myserver.duckdns.org/api/spotify as the redirect URI (which was working well to authorize default ha spotify component.). Added https://myserver.duckdns.org/lovelace/media as an additional redirect URI.
- Using HACS. Tried
- url: /community_plugin/spotify-card/spotify-card.js
  type: module
AND
- type: module
    url: >-
      https://cdn.jsdelivr.net/gh/custom-cards/spotify-card@1.8/dist/spotify-card.umd.js
Not working.
Any advice?

Thanks

**Comment by wzwick** [comment]
Yeah its a tricky one 
Example: https://<your public home assistant hostname>:8123/lovelace/media.
that is really just an example.
where ever you have placed the card - look in the address bar for the correct link (mine was lovelace/2)
then you have to authenticate using the external link ie hassio.local:8123/lovelace wont work
it must be http://yourdomain.duckdns.org:8123/lovelace/2

hope that helps

**Comment by crimean7** [comment]
Now I understood. It worked. Thanks.

**Comment by ha14937** [comment]
@wzwick Apologies if this is the wrong place to address this (in a closed issue) but I cannot find an explanation anywhere - and you've come very close to (I think!) addressing my issue (same as OP) in your comment above.

I have the card on a tab called "media" and the URL is "https://XXXXXXX.duckdns.org:8123/lovelace/media". I've entered that URL in the redirect_uri but it still fails to authenticate. I think your comment above implies the tab you had the card on was an index (rather than the name of the actual Lovelace tab) so I tried using `/lovelace/10` since my media tab has the index of 10 - but no luck. This is the URL from the error page. Any ideas?


https://accounts.spotify.com/authorize?client_id=XXXXXXX&redirect_uri=https://XXXXXXX.duckdns.org:8123/lovelace/media&scope=playlist-read-private%20playlist-read-collaborative%20user-read-playback-state%20user-modify-playback-state&response_type=token

**Comment by wzwick** [comment]
They have actually changed the way it works, have a look here.
https://www.home-assistant.io/integrations/spotify/

so the URL redirect should now be http://xxxxxxxxx.duckdns.org/auth:8123/external/callback

**Comment by ha14937** [comment]
@wzwick sorry, I'm tracking that documentation for the suffix on the URI redirect, I should have typed that out in my initial post. I've tried all of the below as redirect URI's, with a restart of HA in between each, but still get `INVALID_CLIENT: Invalid redirect URI` when I click authenticate from the card.

https://xxxxxxxxx.duckdns.org/auth:8123/external/callback
https://xxxxxxxxx.duckdns.org:8123/auth/external/callback
https://xxxxxxxxx.duckdns.org:8123/lovelace/auth/external/callback
https://xxxxxxxxx.duckdns.org:8123/lovelace/media/auth/external/callback
https://xxxxxxxxx.duckdns.org:8123/lovelace/10/auth/external/callback

I noticed you put the port after /auth:

Was that intentional? I had not seen the port there before. Appreciate the quick response, hope i can get this card working, looks very cool!
